"""add isnew to createimage

Revision ID: 21e129db8695
Revises: ac824e98142b
Create Date: 2024-03-08 14:07:23.333578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # 추가


# revision identifiers, used by Alembic.
revision: str = '21e129db8695'
down_revision: Union[str, None] = 'ac824e98142b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('createimage', sa.Column('isnew', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('createimage', 'isnew')
    # ### end Alembic commands ###
