"""edit created_url text

Revision ID: 308562fe0b8f
Revises: 79110eeb8292
Create Date: 2024-03-11 18:12:44.843340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # 추가
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '308562fe0b8f'
down_revision: Union[str, None] = '79110eeb8292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('createimage', 'created_url',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=400000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('createimage', 'created_url',
               existing_type=sa.Text(length=400000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
