"""edit created_url text

Revision ID: 79110eeb8292
Revises: 61883fee5e85
Create Date: 2024-03-11 17:49:21.670212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # 추가
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '79110eeb8292'
down_revision: Union[str, None] = '61883fee5e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('createimage', 'created_url',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(length=300000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('createimage', 'created_url',
               existing_type=sa.Text(length=300000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
