"""add created_at to CreateImage

Revision ID: ac824e98142b
Revises: beac1f52e511
Create Date: 2024-03-08 10:47:46.596502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # 추가


# revision identifiers, used by Alembic.
revision: str = 'ac824e98142b'
down_revision: Union[str, None] = 'beac1f52e511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fourcharcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sayingcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('createimage', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('createimage', 'created_at')
    op.drop_table('sayingcategory')
    op.drop_table('fourcharcategory')
    # ### end Alembic commands ###
