"""edit image_url from pixabay_image

Revision ID: c11547071642
Revises: 308562fe0b8f
Create Date: 2024-03-12 14:49:07.266241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # 추가
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c11547071642'
down_revision: Union[str, None] = '308562fe0b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('createimage', 'created_url',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=400000),
               existing_nullable=True)
    op.alter_column('pixabaydata', 'imageURL',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(length=300000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pixabaydata', 'imageURL',
               existing_type=sa.Text(length=300000),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('createimage', 'created_url',
               existing_type=sa.Text(length=400000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
