"""add good, bad to saying

Revision ID: cbb20b4340d0
Revises: 21e129db8695
Create Date: 2024-03-08 16:29:58.714527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # 추가


# revision identifiers, used by Alembic.
revision: str = 'cbb20b4340d0'
down_revision: Union[str, None] = '21e129db8695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fourchar', sa.Column('contents_good', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('fourchar', sa.Column('contents_bad', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('saying', sa.Column('contents_good', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('saying', sa.Column('contents_bad', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saying', 'contents_bad')
    op.drop_column('saying', 'contents_good')
    op.drop_column('fourchar', 'contents_bad')
    op.drop_column('fourchar', 'contents_good')
    # ### end Alembic commands ###
